### ISSUE TITLE
 ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’

### ISSUE THREAD

**Issue by xjtdy888** [hustcer/star#42]
npm http 200 https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz
  AR(target) Release/obj.target/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../src/binding.cc:18:
../node_modules/nan/nan.h:316: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
make: **\* [Release/obj.target/iconv/src/binding.o] Error 1
make: Leaving directory `/usr/lib/node_modules/star/node_modules/iconv/build'

**Comment by xjtdy888** [comment]
好像是nodejs版本低了，我升级下看看

**Comment by hustcer** [comment]
@xjtdy888 升级后如何？
