### ISSUE TITLE
如何查看上证、深成指、期指等？

### ISSUE THREAD

**Issue by h1048576** [hustcer/star#52]

**Comment by hustcer** [comment]
这个目前还不支持，后期会考虑加上 😃

**Comment by linyouhappy** [comment]
哈哈无意发现这个开源代码库。表示感谢啊。我也是专业软件开发者和股民。希望可以加入你们队伍。
应该把它开发成web后台比较好，用浏览器显示界面。

**Comment by hustcer** [comment]
@linyouhappy  嗯嗯，欢迎欢迎。至于你说的 web 版，我正在筹划，过段时间应该会有的, 敬请期待

**Comment by linyouhappy** [comment]
应该引进框架设计和主动式挖掘股票AI，加入一些人工智能算法。请问你有资金支持这个项目吗？还是外包呢？

**Comment by hustcer** [comment]
嗯，有一些类似的想法。目前没有资金支持，也不打算外包

**Comment by linyouhappy** [comment]
可以加你的qq或者qq群吗？

**Comment by linyouhappy** [comment]
我也是个人玩，也准备用node.js开发个股票挖掘工具。目前的想法是，用你那套采集数据放入到pomelo-admin-web中。
然后，封装一套框架，然后弄个分析股票的AI，挖掘潜在的短线投资股票。
pomelo-admin-web的网址：
https://github.com/NetEase/pomelo/wiki/pomelo-admin-web%E5%B7%A5%E5%85%B7%E7%9A%84%E4%BD%BF%E7%94%A8

**Comment by hustcer** [comment]
QQ:57396310

**Comment by comeUpWithItLater** [comment]
@linyouhappy  厉害了

**Comment by comeUpWithItLater** [comment]
qq群建好了吗？
