### ISSUE TITLE
ubuntu下安装不成功

### ISSUE THREAD

**Issue by ivernaloo** [hustcer/star#53]
[root@localhost node_modules]# cnpm i -g star
[star@0.3.9] link /root/.nvm/versions/node/v4.4.7/bin/star@ -> ../lib/node_modules/.star_npminstall/star/0.3.9/star/star.js
[star@*] installed at node_modules/.star_npminstall/star/0.3.9/star (176 packages, use 6s, speed 232.74kB/s, json 1.43MB, tarball 0B)
excute post install scripts...
[iconv@2.2.1] scripts.install: "node-gyp rebuild" at ./.star_npminstall/iconv/2.2.1/iconv
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/root/.nvm/versions/node/v4.4.7/lib/node_modules/cnpm/node_modules/npminstall/node_modules/node-gyp/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/root/.nvm/versions/node/v4.4.7/lib/node_modules/cnpm/node_modules/npminstall/node_modules/node-gyp/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/root/.nvm/versions/node/v4.4.7/lib/node_modules/cnpm/node_modules/npminstall/node_modules/node-gyp/node_modules/which/which.js:81:29)
gyp ERR! stack     at /root/.nvm/versions/node/v4.4.7/lib/node_modules/cnpm/node_modules/npminstall/node_modules/node-gyp/node_modules/which/which.js:90:16
gyp ERR! stack     at /root/.nvm/versions/node/v4.4.7/lib/node_modules/cnpm/node_modules/npminstall/node_modules/node-gyp/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /root/.nvm/versions/node/v4.4.7/lib/node_modules/cnpm/node_modules/npminstall/node_modules/node-gyp/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/root/.nvm/versions/node/v4.4.7/bin/node" "/root/.nvm/versions/node/v4.4.7/lib/node_modules/cnpm/node_modules/npminstall/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v4.4.7/lib/node_modules/.star_npminstall/iconv/2.2.1/iconv
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.<anonymous> (/root/.nvm/versions/node/v4.4.7/lib/node_modules/cnpm/node_modules/npminstall/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by ivernaloo** [comment]
现丑了，没装make。。。
apt-get install build-essential 这个装上以后，再安装就没问题了。。
依赖的一些基础编译工具没有装上

**Comment by hustcer** [comment]
嗯嗯，好的，那我 close 了哈。
