### ISSUE TITLE
内部交易的记录和其他用户的投资记录是怎么获取的？　实时的吗？

### ISSUE THREAD

**Issue by joostshao** [hustcer/star#9]
内部交易的记录和其他用户的投资记录是怎么获取的？　实时的吗？

**Comment by joostshao** [comment]
貌似只有纳斯达克的

**Comment by hustcer** [comment]
traceinvest.com 上都是美股的内部交易信息。国内股市的内部交易信息要用 star 工具查询，只能用这个命令行工具，网站上还没有查询界面的，star安装readme里面有说明。

**Comment by joostshao** [comment]
你是在杭州的？　　我也是。。。　　　这是你一个人做的？

**Comment by hustcer** [comment]
en, 是的

**Comment by joostshao** [comment]
这个星期周末的oschina杭州原创会来不来？

**Comment by joostshao** [comment]
有没有联系方式？
